import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from './components/Navbar'
import Homepage from './components/Homepage'
import AboutMe from './components/AboutMe'
import Projects from './components/Projects'
import Skills from './components/Skills'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Monica Narda Davita</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/assets/iconfix.png" />
      </Head>
      <Navbar />
      <Homepage />
      <AboutMe />
      <Projects />
      <Skills />
    </>
  )
}
